apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: hello
  namesapce: lasample 
  labels: 
    app: hello 
    tier: prod 
spec: 
  selector: 
    matchLabels: 
      app: hello 
  template:
    metadata: 
      labels: 
        app: hello 
    spec: 
      containers: 
        - name: hello 
          image: manguilar22/content-gitops:hellov1.2
