apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: hello-qa
  namespace: lasample  
  labels: 
    app : hello 
    tier: qa 
spec: 
  selector: 
    matchLabels:
      app: hello 
  template: 
    metadata:
      labels: 
        app: hello 
    spec: 
      containers: 
        - name: hello 
          image: linuxacademycontent/gitops:hellov1.1 
